var num = "Numbers";
var sign = "$";
var schar = "_";
var letter = "letter";
var sensitive = "sensitive";
document.write("<h1>Rules for naming JS variables</h1><br>");
document.write("Variable names can only contain " + letter + " , " + num + " , " + sign + " and " + schar + " . For example $my_1stVariable.");
document.write("<br>Variables must begin with a "+ letter +" , "+ sign +" or "+ schar +" . For example $name, _name or name.");
document.write("<br>Variable names are case "+ sensitive + ".");
document.write("<br>Variable names should not be JS.");